### ISSUE TITLE
Erroring out during seed generation.

### ISSUE THREAD

**Issue by Oronjoker** [abyssonym/fftrctcr#1]
Seed generation errors out after Traceback with "FileNotFoundError: [Errno 2] No such file or directory: 'temp\BATTLE\\ADORA.SPR"

**Comment by Oronjoker** [comment]
I opened the image and dumped the contents into the partial temp folder the randomizer created and it ran past the initial error but ended up erroring out again at the end with "AttributeError: 'NoneType' object has no attribute 'filesize'" The iso had been expanded in Shishi to allow swapping sprites. I used a fresh iso and it managed to finish. Without manually creating a full temp folder it still errors out however.

**Comment by abyssonym** [comment]
Resolved this issue on discord. An antivirus program was preventing the randomizer from creating temporary files.
